### ISSUE TITLE
Issue with pysam

### ISSUE THREAD

**Issue by roo-weed** [motu-tool/mOTUs_v2#131]
Hello! Thanks for developing this great tool. I'm excited to use it! I am attempting to use for the first time with a new installation and am running into what looks like an issue with pysam. I am running this command:
`python motus.py profile -f /workspace/rweed/TR_phage_redo/13_BLOOMS/buck_db/reads/ERR4193360_1.fastq.gz -r /workspace/rweed/TR_phage_redo/13_BLOOMS/buck_db/reads/ERR4193360_2.fastq.gz -n ERR4193360 -o /workspace/rweed/TR_phage_redo/13_BLOOMS/buck_db/motu_out/ERR4193360.motus -t 32`

And getting the following output:
`2025-01-11,04:06:44 INFO: mOTU tool starting
2025-01-11,04:06:44 INFO: Loading database ... 
2025-01-11,04:07:47 INFO: Loading database finished. Version 4.0 (version date: 2024-08-09) contains 124300 mOTUs, 2075157 markergeneclusters and 3436253 markergenes.
2025-01-11,04:07:47 INFO: Starting mOTUs - map_tax routine - Alignment against the mOTUs database ... 
2025-01-11,04:07:47 INFO: Aligning /workspace/rweed/TR_phage_redo/13_BLOOMS/buck_db/reads/ERR4193360_1.fastq.gz
Traceback (most recent call last):
  File "motus.py", line 2331, in <module>
    parse_profile()
  File "motus.py", line 1906, in parse_profile
    map_tax()
  File "motus.py", line 1089, in map_tax
    in_bam_file_handle = pysam.AlignmentFile(process.stdout, 'rb')
  File "pysam/calignmentfile.pyx", line 311, in pysam.calignmentfile.AlignmentFile.__cinit__ (pysam/calignmentfile.c:4929)
  File "pysam/calignmentfile.pyx", line 393, in pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:6013)
  File "pysam/calignmentfile.pyx", line 60, in pysam.calignmentfile._encodeFilename (pysam/calignmentfile.c:3593)
TypeError: Argument must be string or unicode.`

Let me know if you have any advice! Thank you so much!
-Roo

**Comment by roo-weed** [comment]
As an update: I just tried deleting and re-installing pysam and re-ran, and I got a different error:
`2025-01-12,03:55:12 INFO: mOTU tool starting
2025-01-12,03:55:12 INFO: Loading database ...
2025-01-12,03:56:14 INFO: Loading database finished. Version 4.0 (version date: 2024-08-09) contains 124300 mOTUs, 2075157 markergeneclusters and 3436253 markergenes.
2025-01-12,03:56:14 INFO: Starting mOTUs - map_tax routine - Alignment against the mOTUs database ...
2025-01-12,03:56:14 INFO: Aligning /workspace/rweed/TR_phage_redo/13_BLOOMS/buck_db/reads/ERR4193360_1.fastq.gz
2025-01-12,04:11:54 INFO: Finished alignment. Total reads: 47881362, Total aligned reads 113312, 0.2367% aligned.
2025-01-12,04:11:54 INFO: Aligning /workspace/rweed/TR_phage_redo/13_BLOOMS/buck_db/reads/ERR4193360_2.fastq.gz
2025-01-12,04:27:27 INFO: Finished alignment. Total reads: 47881362, Total aligned reads 113005, 0.236% aligned.
2025-01-12,04:27:27 INFO: Finished all alignments. Total reads: 95762724, Total aligned reads 226317, 0.2363%
2025-01-12,04:27:28 INFO: Sorting BAM file
2025-01-12,04:27:42 INFO: Finished sorting BAM file
Traceback (most recent call last):
  File "motus.py", line 2331, in <module>
    parse_profile()
  File "motus.py", line 1906, in parse_profile
    map_tax()
  File "motus.py", line 1147, in map_tax
    motusfiles.delete_temporary_alignment_file()
  File "motus.py", line 603, in delete_temporary_alignment_file
    self._temp_alignment_file.unlink(missing_ok=True)
TypeError: unlink() got an unexpected keyword argument 'missing_ok'`

The run seems to have made it further this time. Thanks for your help!

-Roo

**Comment by hjruscheweyh** [comment]
Hi @roo-weed

Thank you for using the motus tool. Can you share the versions of Python and Pysam please?

best and thanks,
Hans

**Comment by roo-weed** [comment]
Hello Hans, 

Thanks for your response! I got it working with python 3.10.11 and 0.21! I had been struggling to install such an old version of pysam. Thanks for your help!

-Roo

**Comment by hjruscheweyh** [comment]
Great, thanks

We will update the documentation to include proper dependencies.

Best
Hans
